let productsbb = [
  {
    id: 1,
    imageurl: "images/1e916d6cd44ce8645bf69fa21cbc0258.jpg",
    product: "Training",
    price: "400$",
    catagory: "fashion",
    qty: 1,
  },
  {
    id: 2,
    imageurl: "images/training.jpg",
    product: "Training",
    price: "250$",
    catagory: "fashion",
    qty: 1,
  },
  {
    id: 3,
    imageurl: "images/shirt.jpg",
    product: "shirt",
    price: "550$",
    catagory: "fashion",
    qty: 1,
  },
  {
    id: 4,
    imageurl: "images/58ccf0b8588653f63f55e93dc68d7cd0.jpg",
    product: "suit",
    price: "440$",
    catagory: "classic",
    qty: 1,
  },
  {
    id: 5,
    imageurl: "images/612ZychwHkL._AC_SY879_.jpg",
    product: "shirt",
    price: "150$",
    catagory: "classic",
    qty: 1,
  },
  {
    id: 6,
    imageurl: "images/training2.png",
    product: "training",
    price: "440$",
    catagory: "fashion",
    qty: 1,
  },
  {
    id: 7,
    imageurl: "images/61FNkjA2bHL._AC_SX679_.jpg",
    product: "suit",
    price: "200$",
    catagory: "classic",
    qty: 1,
  },
  {
    id: 8,
    imageurl: "images/31cs6PMOwSL._AC_.jpg",
    product: "suit",
    price: "200$",
    catagory: "classic",
    qty: 1,
  },
  {
    id: 9,
    imageurl: "images/jeans.avif",
    product: "jeans",
    price: "150$",
    catagory: "fashion",
    qty: 1,
  },
];
